name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=2.2.4
  - pandas=2.2.3
  - panel=1.6.2
  - pip=25.0.1
  - pytest=8.3.5
  - python=3.12.9
  - pyyaml=6.0.2
  - typing_extensions=4.13.1
  - wheel=0.45.1
  - pip:
      - kaleido==0.2.1
      - matplotlib==3.10.1
      - mlflow==2.21.3
      - mlflow-skinny==2.21.3
      - optuna==4.2.1
      - optuna-integration==4.2.1
      - pandas-stubs==2.2.3.250308
      - plotly==6.0.1
      - scikit-learn==1.6.1
      - shap==0.47.2
      - xgboost==3.0.0
